version: "3.5"

services:
  backend:
    image: node:14
    command: bash -c "yarn install && yarn knex migrate:latest && yarn start"
    working_dir: /usr/app
    volumes:
      - ./backend:/usr/app
    ports:
      - "3333:3333"


  react-frontend:
    tty: true
    image: node:14
    command: bash -c "yarn install && yarn start"
    working_dir: /usr/app
    volumes:
      - ./react-frontend:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.77.0.0/16